sources:
  - url: "https://www.lancedb.com/blog"
    pattern: |
      <div role="listitem" class="w-dyn-item"><a href="{%}"{*}<div class="search-post-heading">{%}</div><div class="search-post_description">{%}</div>
    title_template: "{%2}"
    link_template: "{%1}"
    content_template: "{%3}"
    feed_title: "LanceDB Blog"
    feed_link: "https://www.lancedb.com/blog"
    feed_description: "LanceDB Blog Feed"
  - url: "https://flink.apache.org/posts/" 
    pattern: |
      <article class="markdown book-post">{*}<h3>{*}<a href="{%}">{%}</a>{*}</h3>{%}</article>
    title_template: "{%2}"
    link_template: "{%1}"
    content_template: "{%3}"
    feed_title: "Apache Flink Blog"
    feed_link: "https://flink.apache.org/posts/"
    feed_description: "Apache Flink Blog Feed"
  - url: "https://www.anthropic.com/engineering"
    pattern: |
      <h3 class="headline-4">{%}</h3>{*}<a class="ArticleList-module-scss-module___tpu-a__cardLink" href="{%}">
    title_template: "{%1}"
    link_template: "{%2}"
    feed_title: "Anthropic Engineering Blog"
    feed_link: "https://www.anthropic.com/engineering"
    feed_description: "Engineering at Anthropic: Inside the team building reliable AI systems"
  - url: "https://qoder.com/zh/blog"
    pattern: |
      {\"title\":\"{%}\",\"desc\":\"{%}\",\"img\{*}\"url\":\"{%}\",\"published_at
    title_template: "{%1}"
    link_template: "https://qoder.com/zh/blog/{%3}"
    content_template: "{%2}"
    feed_title: "Qoder Blog | 智能体编程平台"
    feed_link: "https://qoder.com/zh/blog"
    feed_description: "Qoder Blog: 智能体编程平台的最新动态"